docs: move to github pages
HaylLtd/cordova-plugin-background-geolocation pull request #35
Opened 2021-06-02 09:53 UTC by RaddishIoW

2021-06-02 12:41 UTC, HarelM requested changes

2021-06-02 12:41 UTC, HarelM commented on README.md
> +### Cross-platform geolocation for Cordova / PhoneGap with battery-saving "circular region monitoring" and "stop detection"
Remove PhoneGap?

2021-06-02 12:41 UTC, HarelM commented on README.md
> +The notification can only be disabled, when app is running in the foreground, by setting config option `startForeground: false` (this is the default option), but will always be visible in the backgro
Cool! good work!

2021-06-21 21:05 UTC, RaddishIoW commented on README.md
> +### Cross-platform geolocation for Cordova / PhoneGap with battery-saving "circular region monitoring" and "stop detection"
Done

2021-06-21 21:09 UTC, merged

2021-06-21 21:14 UTC, HarelM approved these changes
Amazing work!!